version: '3.1'

services:

  db:
    image: postgres:15.1-alpine
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hedera_hashproof
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  app:
    build: 
      context: .
    restart: on-failure
    env_file:
      - .env
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/hedera_hashproof
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - db